[package]
name = "ash-nv-rt"
version = "0.1.1"
authors = ["Graham Wihlidal <graham@wihlidal.ca>"]
edition = "2018"

[dependencies]
ash = "0.28.0"
winit = "0.19"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.6", features = ["windef", "winuser"] }